apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications

  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/sleepr-414922/notifications/production
          name: notifications
          env:
            - name: TCP_PORT
              value: '5002'
            - name: GOOGLE_OAUTH_CLIENT_ID
              value: 337290724144-et0ltmn2mqbb5c5s2eme7hi0ddiualh7.apps.googleusercontent.com
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google
                  key: clientSecret
            - name: GOOGLE_OAUTH_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google
                  key: refreshToken
            - name: SMTP_USER
              value: a.adeniranomobolaji@gmail.com
          ports:
            - containerPort: 5002
