apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  ports:
  - name: "tcp"
    port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    app: notifications
  type: ClusterIP

