steps:
  #reservations
  - name: 'gcr.io/cloud-builders/docker'
    args: [
     'build',
     '-t',
     'europe-west1-docker.pkg.dev/sleepr-414922/reservations/production',
     '-f',
     'apps/reservations/Dockerfile',
     '.'
     ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
     'push',
     'europe-west1-docker.pkg.dev/sleepr-414922/reservations/production',
     ]

 #auth
  - name: 'gcr.io/cloud-builders/docker'
    args: [
     'build',
     '-t',
     'europe-west1-docker.pkg.dev/sleepr-414922/auth/production',
     '-f',
     'apps/auth/Dockerfile',
     '.'
     ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
     'push',
     'europe-west1-docker.pkg.dev/sleepr-414922/auth/production',
     ]

 #payments
  - name: 'gcr.io/cloud-builders/docker'
    args: [
     'build',
     '-t',
     'europe-west1-docker.pkg.dev/sleepr-414922/payments/production',
     '-f',
     'apps/payments/Dockerfile',
     '.'
     ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
     'push',
     'europe-west1-docker.pkg.dev/sleepr-414922/payments/production',
     ]

  #notifications
  - name: 'gcr.io/cloud-builders/docker'
    args: [
     'build',
     '-t',
     'europe-west1-docker.pkg.dev/sleepr-414922/notifications/production',
     '-f',
     'apps/notifications/Dockerfile',
     '.'
     ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
     'push',
     'europe-west1-docker.pkg.dev/sleepr-414922/notifications/production',
     ]