apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-tcp
spec:
  ports:
  - name: "tcp"
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: auth
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-http
spec:
  ports:
  - name: "http"
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: auth
  type: NodePort

