services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/app/specs
    depends_on:
      - mongo
      - reservations
      - auth
      - payments
      - notifications

  reservations:
    image: europe-west1-docker.pkg.dev/sleepr-414922/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'

  auth:
    image: europe-west1-docker.pkg.dev/sleepr-414922/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
      - '5000:5000'

  payments:
    image: europe-west1-docker.pkg.dev/sleepr-414922/payments/production
    ports:
      - '5001:5001'
    env_file:
      - ../apps/payments/.env

  notifications:
    image: europe-west1-docker.pkg.dev/sleepr-414922/notifications/production
    ports:
      - '5002:5002'
    env_file:
      - ../apps/notifications/.env

  mongo:
    image: mongo
